---
- name: get consoleUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .consoleUrl
  register: vz_url_console_result
- name: get elasticUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .elasticUrl
  register: vz_url_elasticUrl_result
- name: get grafanaUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .grafanaUrl
  register: vz_url_grafanaUrl_result  
- name: get keyCloakUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .keyCloakUrl
  register: vz_url_keyCloakUrl_result  
- name: get kialiUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .kialiUrl
  register: vz_url_kialiUrl_result  
- name: get kibanaUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .kibanaUrl
  register: vz_url_kibanaUrl_result  
- name: get prometheusUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .prometheusUrl
  register: vz_url_prometheusUrl_result 
- name: get rancherUrl
  shell: |
    kubectl get vz -o jsonpath="{.items[].status.instance}" | jq -r .rancherUrl
  register: vz_url_rancherUrl_result 
- name: Gather EXTERNAL_IP
  shell: |
    kubectl get service -n "istio-system" "istio-ingressgateway" -o jsonpath={.status.loadBalancer.ingress[0].ip}
  register: ext_ip_result
- name: Gather Verrazzano Console Password
  shell: |
    kubectl get secret --namespace verrazzano-system verrazzano -o jsonpath={.data.password} | base64 --decode; echo
  register: vz_pass_result
- name: set facts
  set_fact:
    vz_console_url: "{{ vz_url_console_result.stdout }}"
    vz_elasticUrl_url: "{{ vz_url_elasticUrl_result.stdout }}"
    vz_grafanaUrl_url: "{{ vz_url_grafanaUrl_result.stdout }}"
    vz_keyCloakUrl_url: "{{ vz_url_keyCloakUrl_result.stdout }}"
    vz_kialiUrl_url: "{{ vz_url_kialiUrl_result.stdout }}"
    vz_kibanaUrl_url: "{{ vz_url_kibanaUrl_result.stdout }}"
    vz_prometheusUrl_url: "{{ vz_url_prometheusUrl_result.stdout }}"
    roberts_book_store_url: "https://bobs-books.bobs-books.{{ ext_ip_result.stdout }}.nip.io/"
    bobs_book_store_url: "https://bobs-books.bobs-books.{{ ext_ip_result.stdout }}.nip.io/bobbys-front-end/"
    bobs_order_manager_url: "https://bobs-books.bobs-books.{{ ext_ip_result.stdout }}.nip.io/bobs-bookstore-order-manager/orders"
    vz_console_pass: "{{ vz_pass_result.stdout }}"
- name: print facts
  debug:
    var: "{{ item }}"
  loop: 
    - vz_console_url
    - vz_elasticUrl_url
    - vz_grafanaUrl_url
    - vz_keyCloakUrl_url
    - vz_kialiUrl_url
    - vz_kibanaUrl_url
    - vz_prometheusUrl_url
    - roberts_book_store_url
    - bobs_book_store_url
    - bobs_order_manager_url
    - vz_console_pass
- name: generate bookmarks.html
  template:
    src: templates/bookmark-import.j2
    dest: $HOME/Desktop/bookmarks.html