---
- name: Download app images from Oracle registry
  uri:
    url: "https://raw.githubusercontent.com/verrazzano/verrazzano/v{{ v8o_version }}/examples/bobs-books/{{ item }}"
    creates: "{{ playbook_dir }}/roles/deploy-apps/files/{{ item }}"
    dest: "{{ playbook_dir }}/roles/deploy-apps/files/{{ item }}"
  register: app_result
  loop:
    - bobs-books-app.yaml
    - bobs-books-comp.yaml
- name: create namespace config for bobs-books
  template: 
    src: templates/namespace.j2
    dest: "{{ playbook_dir }}/roles/deploy-apps/files/namespace.yml"
  vars:
    namespace: bobs-books
    labels: 
      - 'verrazzano-managed: "true"'
      - 'istio-injection: enabled'
- name: apply kubernetes objects
  shell: |
    kubectl apply -f {{ playbook_dir }}/roles/deploy-apps/files/{{ item }}
  loop:
    - namespace.yml
# - name: Download create_secret.sh script
#   uri:
#     url: "https://raw.githubusercontent.com/oracle/learning-library/master/developer-library/multicloud/verrazzano/deploy-bobsbook/create_secret.sh"
#     creates: "{{ playbook_dir }}/roles/deploy-apps/files/create_secret.sh"
#     dest: "{{ playbook_dir }}/roles/deploy-apps/files/create_secret.sh"
#     mode: 0777
#   register: secret_result
- name: prepare .config
  file:
    path: ${HOME}/.config/containers
    state: directory
- name: configure auth.json
  template:
    src: templates/auth.j2
    dest: ${HOME}/.config/containers/auth.json
    mode: 0600
- name: check if bobs-books-repo-credentials secret already exists
  shell: |
    kubectl get secret bobs-books-repo-credentials -n bobs-books --no-headers | grep -ci bobs-books-repo-credentials
  register: secret_check
  ignore_errors: true
- name: create bobs-books-repo-credentials secret
  shell: |
    kubectl create secret docker-registry bobs-books-repo-credentials  --docker-server=container-registry.oracle.com  --docker-username={{ my_registry_user }} --docker-password={{ my_registry_pass }} --docker-email=$1  -n bobs-books
  register: create_secret_result
  when: secret_check.stdout == "0"
  failed_when: "'secret/bobs-books-repo-credentials created' not in create_secret_result.stdout"
- name: check if bobbys-front-end-weblogic-credentials secret already exists
  shell: |
    kubectl get secret bobbys-front-end-weblogic-credentials -n bobs-books --no-headers | grep -ci bobs-books-repo-credentials
  register: secret2_check
  ignore_errors: true
- name: create bobbys-front-end-weblogic-credentials secret
  shell: |
    kubectl create secret generic bobbys-front-end-weblogic-credentials --from-literal=password="{{ wls_password }}" --from-literal=username={{ wls_username }} -n bobs-books
  register: create_secret2_result
  when: secret2_check.stdout == "0"
  failed_when: "'secret/bobbys-front-end-weblogic-credentials created' not in create_secret2_result.stdout"

- name: check if bobs-bookstore-weblogic-credentials secret already exists
  shell: |
    kubectl get secret bobs-bookstore-weblogic-credentials -n bobs-books --no-headers | grep -ci bobs-bookstore-weblogic-credentials
  register: secret3_check
  ignore_errors: true
- name: create bobs-bookstore-weblogic-credentials secret
  shell: |
    kubectl create secret generic bobs-bookstore-weblogic-credentials --from-literal=password="{{ wls_password }}" --from-literal=username={{ wls_username }} -n bobs-books
  register: create_secret3_result
  when: secret3_check.stdout == "0"
  failed_when: "'secret/bobs-bookstore-weblogic-credentials created' not in create_secret3_result.stdout"

- name: check if mysql-credentials secret already exists
  shell: |
    kubectl get secret mysql-credentials -n bobs-books --no-headers | grep -ci mysql-credentials
  register: secret4_check
  ignore_errors: true
- name: create mysql-credentials secret
  shell: |
    kubectl create secret generic mysql-credentials --from-literal=password="{{ wls_password }}" --from-literal=username={{ wls_username }} --from-literal=url=jdbc:mysql://mysql.bobs-books.svc.cluster.local:3306/books -n bobs-books
  register: create_secret4_result
  when: secret3_check.stdout == "0"
  failed_when: "'secret/mysql-credentials created' not in create_secret4_result.stdout"
